const countries = [
	{ name: 'Afghanistan', code: '+93', short_name: 'AFG' },
	{ name: 'Albania', code: '+355', short_name: 'ALB' },
	{ name: 'Algeria', code: '+213', short_name: 'DZA' },
	{ name: 'Andorra', code: '+376', short_name: 'AND' },
	{ name: 'Angola', code: '+244', short_name: 'AGO' },
	{ name: 'Antigua and Barbuda', code: '+1-268', short_name: 'ATG' },
	{ name: 'Argentina', code: '+54', short_name: 'ARG' },
	{ name: 'Armenia', code: '+374', short_name: 'ARM' },
	{ name: 'Australia', code: '+61', short_name: 'AUS' },
	{ name: 'Austria', code: '+43', short_name: 'AUT' },
	{ name: 'Azerbaijan', code: '+994', short_name: 'AZE' },
	{ name: 'Bahamas', code: '+1-242', short_name: 'BHS' },
	{ name: 'Bahrain', code: '+973', short_name: 'BHR' },
	{ name: 'Bangladesh', code: '+880', short_name: 'BGD' },
	{ name: 'Barbados', code: '+1-246', short_name: 'BRB' },
	{ name: 'Belarus', code: '+375', short_name: 'BLR' },
	{ name: 'Belgium', code: '+32', short_name: 'BEL' },
	{ name: 'Belize', code: '+501', short_name: 'BLZ' },
	{ name: 'Benin', code: '+229', short_name: 'BEN' },
	{ name: 'Bhutan', code: '+975', short_name: 'BTN' },
	{ name: 'Bolivia', code: '+591', short_name: 'BOL' },
	{ name: 'Bosnia and Herzegovina', code: '+387', short_name: 'BIH' },
	{ name: 'Botswana', code: '+267', short_name: 'BWA' },
	{ name: 'Brazil', code: '+55', short_name: 'BRA' },
	{ name: 'Brunei Darussalam', code: '+673', short_name: 'BRN' },
	{ name: 'Bulgaria', code: '+359', short_name: 'BGR' },
	{ name: 'Burkina Faso', code: '+226', short_name: 'BFA' },
	{ name: 'Burundi', code: '+257', short_name: 'BDI' },
	{ name: 'Cabo Verde', code: '+238', short_name: 'CPV' },
	{ name: 'Cambodia', code: '+855', short_name: 'KHM' },
	{ name: 'Cameroon', code: '+237', short_name: 'CMR' },
	{ name: 'Canada', code: '+1', short_name: 'CAN' },
	{ name: 'Central African Republic', code: '+236', short_name: 'CAF' },
	{ name: 'Chad', code: '+235', short_name: 'TCD' },
	{ name: 'Chile', code: '+56', short_name: 'CHL' },
	{ name: 'China', code: '+86', short_name: 'CHN' },
	{ name: 'Colombia', code: '+57', short_name: 'COL' },
	{ name: 'Comoros', code: '+269', short_name: 'COM' },
	{ name: 'Congo (Congo-Brazzaville)', code: '+242', short_name: 'COG' },
	{ name: 'Congo (Democratic Republic of the)', code: '+243', short_name: 'COD' },
	{ name: 'Costa Rica', code: '+506', short_name: 'CRI' },
	{ name: 'Croatia', code: '+385', short_name: 'HRV' },
	{ name: 'Cuba', code: '+53', short_name: 'CUB' },
	{ name: 'Cyprus', code: '+357', short_name: 'CYP' },
	{ name: 'Czechia (Czech Republic)', code: '+420', short_name: 'CZE' },
	{ name: 'Denmark', code: '+45', short_name: 'DNK' },
	{ name: 'Djibouti', code: '+253', short_name: 'DJI' },
	{ name: 'Dominica', code: '+1-767', short_name: 'DMA' },
	{ name: 'Dominican Republic', code: '+1-809', short_name: 'DOM' },
	{ name: 'Ecuador', code: '+593', short_name: 'ECU' },
	{ name: 'Egypt', code: '+20', short_name: 'EGY' },
	{ name: 'El Salvador', code: '+503', short_name: 'SLV' },
	{ name: 'Equatorial Guinea', code: '+240', short_name: 'GNQ' },
	{ name: 'Eritrea', code: '+291', short_name: 'ERI' },
	{ name: 'Estonia', code: '+372', short_name: 'EST' },
	{ name: 'Eswatini (fmr. "Swaziland")', code: '+268', short_name: 'SWZ' },
	{ name: 'Ethiopia', code: '+251', short_name: 'ETH' },
	{ name: 'Fiji', code: '+679', short_name: 'FJI' },
	{ name: 'Finland', code: '+358', short_name: 'FIN' },
	{ name: 'France', code: '+33', short_name: 'FRA' },
	{ name: 'Gabon', code: '+241', short_name: 'GAB' },
	{ name: 'Gambia', code: '+220', short_name: 'GMB' },
	{ name: 'Georgia', code: '+995', short_name: 'GEO' },
	{ name: 'Germany', code: '+49', short_name: 'DEU' },
	{ name: 'Ghana', code: '+233', short_name: 'GHA' },
	{ name: 'Greece', code: '+30', short_name: 'GRC' },
	{ name: 'Grenada', code: '+1-473', short_name: 'GRD' },
	{ name: 'Guatemala', code: '+502', short_name: 'GTM' },
	{ name: 'Guinea', code: '+224', short_name: 'GIN' },
	{ name: 'Guinea-Bissau', code: '+245', short_name: 'GNB' },
	{ name: 'Guyana', code: '+592', short_name: 'GUY' },
	{ name: 'Haiti', code: '+509', short_name: 'HTI' },
	{ name: 'Honduras', code: '+504', short_name: 'HND' },
	{ name: 'Hungary', code: '+36', short_name: 'HUN' },
	{ name: 'Iceland', code: '+354', short_name: 'ISL' },
	{ name: 'India', code: '+91', short_name: 'IND' },
	{ name: 'Indonesia', code: '+62', short_name: 'IDN' },
	{ name: 'Iran', code: '+98', short_name: 'IRN' },
	{ name: 'Iraq', code: '+964', short_name: 'IRQ' },
	{ name: 'Ireland', code: '+353', short_name: 'IRL' },
	{ name: 'Israel', code: '+972', short_name: 'ISR' },
	{ name: 'Italy', code: '+39', short_name: 'ITA' },
	{ name: 'Jamaica', code: '+1-876', short_name: 'JAM' },
	{ name: 'Japan', code: '+81', short_name: 'JPN' },
	{ name: 'Jordan', code: '+962', short_name: 'JOR' },
	{ name: 'Kazakhstan', code: '+7', short_name: 'KAZ' },
	{ name: 'Kenya', code: '+254', short_name: 'KEN' },
	{ name: 'Kiribati', code: '+686', short_name: 'KIR' },
	{ name: 'Korea (North)', code: '+850', short_name: 'PRK' },
	{ name: 'Korea (South)', code: '+82', short_name: 'KOR' },
	{ name: 'Kuwait', code: '+965', short_name: 'KWT' },
	{ name: 'Kyrgyzstan', code: '+996', short_name: 'KGZ' },
	{ name: 'Laos', code: '+856', short_name: 'LAO' },
	{ name: 'Latvia', code: '+371', short_name: 'LVA' },
	{ name: 'Lebanon', code: '+961', short_name: 'LBN' },
	{ name: 'Lesotho', code: '+266', short_name: 'LSO' },
	{ name: 'Liberia', code: '+231', short_name: 'LBR' },
	{ name: 'Libya', code: '+218', short_name: 'LBY' },
	{ name: 'Liechtenstein', code: '+423', short_name: 'LIE' },
	{ name: 'Lithuania', code: '+370', short_name: 'LTU' },
	{ name: 'Luxembourg', code: '+352', short_name: 'LUX' },
	{ name: 'Madagascar', code: '+261', short_name: 'MDG' },
	{ name: 'Malawi', code: '+265', short_name: 'MWI' },
	{ name: 'Malaysia', code: '+60', short_name: 'MYS' },
	{ name: 'Maldives', code: '+960', short_name: 'MDV' },
	{ name: 'Mali', code: '+223', short_name: 'MLI' },
	{ name: 'Malta', code: '+356', short_name: 'MLT' },
	{ name: 'Marshall Islands', code: '+692', short_name: 'MHL' },
	{ name: 'Mauritania', code: '+222', short_name: 'MRT' },
	{ name: 'Mauritius', code: '+230', short_name: 'MUS' },
	{ name: 'Mexico', code: '+52', short_name: 'MEX' },
	{ name: 'Micronesia', code: '+691', short_name: 'FSM' },
	{ name: 'Moldova', code: '+373', short_name: 'MDA' },
	{ name: 'Monaco', code: '+377', short_name: 'MCO' },
	{ name: 'Mongolia', code: '+976', short_name: 'MNG' },
	{ name: 'Montenegro', code: '+382', short_name: 'MNE' },
	{ name: 'Morocco', code: '+212', short_name: 'MAR' },
	{ name: 'Mozambique', code: '+258', short_name: 'MOZ' },
	{ name: 'Myanmar', code: '+95', short_name: 'MMR' },
	{ name: 'Namibia', code: '+264', short_name: 'NAM' },
	{ name: 'Nauru', code: '+674', short_name: 'NRU' },
	{ name: 'Nepal', code: '+977', short_name: 'NPL' },
	{ name: 'Netherlands', code: '+31', short_name: 'NLD' },
	{ name: 'New Zealand', code: '+64', short_name: 'NZL' },
	{ name: 'Nicaragua', code: '+505', short_name: 'NIC' },
	{ name: 'Niger', code: '+227', short_name: 'NER' },
	{ name: 'Nigeria', code: '+234', short_name: 'NGA' },
	{ name: 'North Macedonia', code: '+389', short_name: 'MKD' },
	{ name: 'Norway', code: '+47', short_name: 'NOR' },
	{ name: 'Oman', code: '+968', short_name: 'OMN' },
	{ name: 'Pakistan', code: '+92', short_name: 'PAK' },
	{ name: 'Palau', code: '+680', short_name: 'PLW' },
	{ name: 'Panama', code: '+507', short_name: 'PAN' },
	{ name: 'Papua New Guinea', code: '+675', short_name: 'PNG' },
	{ name: 'Paraguay', code: '+595', short_name: 'PRY' },
	{ name: 'Peru', code: '+51', short_name: 'PER' },
	{ name: 'Philippines', code: '+63', short_name: 'PHL' },
	{ name: 'Poland', code: '+48', short_name: 'POL' },
	{ name: 'Portugal', code: '+351', short_name: 'PRT' },
	{ name: 'Qatar', code: '+974', short_name: 'QAT' },
	{ name: 'Romania', code: '+40', short_name: 'ROU' },
	{ name: 'Russia', code: '+7', short_name: 'RUS' },
	{ name: 'Rwanda', code: '+250', short_name: 'RWA' },
	{ name: 'Saint Kitts and Nevis', code: '+1-869', short_name: 'KNA' },
	{ name: 'Saint Lucia', code: '+1-758', short_name: 'LCA' },
	{ name: 'Saint Vincent and the Grenadines', code: '+1-784', short_name: 'VCT' },
	{ name: 'Samoa', code: '+685', short_name: 'WSM' },
	{ name: 'San Marino', code: '+378', short_name: 'SMR' },
	{ name: 'Sao Tome and Principe', code: '+239', short_name: 'STP' },
	{ name: 'Saudi Arabia', code: '+966', short_name: 'SAU' },
	{ name: 'Senegal', code: '+221', short_name: 'SEN' },
	{ name: 'Serbia', code: '+381', short_name: 'SRB' },
	{ name: 'Seychelles', code: '+248', short_name: 'SYC' },
	{ name: 'Sierra Leone', code: '+232', short_name: 'SLE' },
	{ name: 'Singapore', code: '+65', short_name: 'SGP' },
	{ name: 'Slovakia', code: '+421', short_name: 'SVK' },
	{ name: 'Slovenia', code: '+386', short_name: 'SVN' },
	{ name: 'Solomon Islands', code: '+677', short_name: 'SLB' },
	{ name: 'Somalia', code: '+252', short_name: 'SOM' },
	{ name: 'South Africa', code: '+27', short_name: 'ZAF' },
	{ name: 'South Sudan', code: '+211', short_name: 'SSD' },
	{ name: 'Spain', code: '+34', short_name: 'ESP' },
	{ name: 'Sri Lanka', code: '+94', short_name: 'LKA' },
	{ name: 'Sudan', code: '+249', short_name: 'SDN' },
	{ name: 'Suriname', code: '+597', short_name: 'SUR' },
	{ name: 'Sweden', code: '+46', short_name: 'SWE' },
	{ name: 'Switzerland', code: '+41', short_name: 'CHE' },
	{ name: 'Syria', code: '+963', short_name: 'SYR' },
	{ name: 'Taiwan', code: '+886', short_name: 'TWN' },
	{ name: 'Tajikistan', code: '+992', short_name: 'TJK' },
	{ name: 'Tanzania', code: '+255', short_name: 'TZA' },
	{ name: 'Thailand', code: '+66', short_name: 'THA' },
	{ name: 'Timor-Leste', code: '+670', short_name: 'TLS' },
	{ name: 'Togo', code: '+228', short_name: 'TGO' },
	{ name: 'Tonga', code: '+676', short_name: 'TON' },
	{ name: 'Trinidad and Tobago', code: '+1-868', short_name: 'TTO' },
	{ name: 'Tunisia', code: '+216', short_name: 'TUN' },
	{ name: 'Turkey', code: '+90', short_name: 'TUR' },
	{ name: 'Turkmenistan', code: '+993', short_name: 'TKM' },
	{ name: 'Tuvalu', code: '+688', short_name: 'TUV' },
	{ name: 'Uganda', code: '+256', short_name: 'UGA' },
	{ name: 'Ukraine', code: '+380', short_name: 'UKR' },
	{ name: 'United Arab Emirates', code: '+971', short_name: 'ARE' },
	{ name: 'United Kingdom', code: '+44', short_name: 'GBR' },
	{ name: 'United States', code: '+1', short_name: 'USA' },
	{ name: 'Uruguay', code: '+598', short_name: 'URY' },
	{ name: 'Uzbekistan', code: '+998', short_name: 'UZB' },
	{ name: 'Vanuatu', code: '+678', short_name: 'VUT' },
	{ name: 'Vatican City', code: '+379', short_name: 'VAT' },
	{ name: 'Venezuela', code: '+58', short_name: 'VEN' },
	{ name: 'Vietnam', code: '+84', short_name: 'VNM' },
	{ name: 'Yemen', code: '+967', short_name: 'YEM' },
	{ name: 'Zambia', code: '+260', short_name: 'ZMB' },
	{ name: 'Zimbabwe', code: '+263', short_name: 'ZWE' },
]

module.exports = { countries }
