const collections = {
	schools: 'schools',
	classrooms: 'classrooms',
	baselineRecords: 'baselinerecords',
	individualRecords: 'individualrecords',
	observationRecords: 'observationrecords',
	SELCurriculumTracker: 'selcurriculumtrackers',
	studentCheckList: 'studentchecklists',
	miscellaneous: 'miscellaneous',
	mypeeguMessages: 'mypeegu_messages',
	mypeeguPermissions: 'mypeegu_permissions',
	globalMessages: 'global_messages',
	mypeeguAppfeatures: 'mypeegu_appfeatures',
	mypeeguPermission_ops: 'mypeegu_permission_ops',
	students: 'students',
	studentsHistory: 'studentshistories',
	studentCopeAssessment: 'studentcopeassessments',
	educationPlanner: 'educationplanners',
	studentsWellBeingAssessment: 'studentswellbeingassessments',
	teacher: 'teachers',
	mypeeguUsers: 'mypeegusers',
	mypeeguUsersHistory: 'mypeeguuserhistories',
	mypeeguUserTokens: 'mypeeguusertokens',
	schoolTeacher: 'schoolteachers',
	academicYears: 'academic-years',
	schoolAcademicYears: 'school-academic-years',
	countries: 'countries',
	states: 'states',
	selModules: 'sel-modules',
	profilingForSchools: 'profiling-for-schools',
	iriForSchools: 'iri-for-schools',
	profilingForTeachers: 'profiling-for-teachers',
	iriForTeachers: 'iri-for-teachers',
	gandtTemplates: 'gandt-templates',
	gandtAssignments: 'gandt-assignments',
	gandtAssessments: 'gandt-assessments',
	users: 'mypeegusers',
}

const years = [
	'2020',
	'2021',
	'2022',
	'2023',
	'2024',
	'2025',
	'2026',
	'2027',
	'2028',
	'2029',
	'2030',
]

module.exports.collections = collections
module.exports.years = years
